# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-21 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'purchase',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Verified', 'Verified'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Open', max_length=25)),
                ('created_at', models.DateTimeField()),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Purchase')),
            ],
            options={
                'db_table': 'purchase_status',
                'ordering': ['pk'],
            },
        ),
    ]
